# Generated by Django 2.0 on 2017-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admininfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='admin name')),
                ('password', models.CharField(max_length=20, verbose_name='admin password')),
                ('signdate', models.DateField(verbose_name='sign date')),
                ('interestnum', models.IntegerField(verbose_name='luckly number')),
            ],
        ),
    ]
