# Generated by Django 2.0 on 2018-01-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
        ('userinfo', '0001_initial'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('auth', models.CharField(max_length=10, verbose_name='作者')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifytime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messtime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User')),
            ],
        ),
    ]
