# Generated by Django 2.0 on 2018-01-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='userinfo name')),
                ('password', models.CharField(max_length=20, verbose_name='userinfo password')),
                ('signdate', models.DateTimeField(verbose_name='sign date')),
                ('interestnum', models.IntegerField(verbose_name='luckly number')),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
    ]
