# Generated by Django 2.0 on 2018-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='userinfo name')),
                ('password', models.CharField(max_length=20, verbose_name='userinfo password')),
                ('signdate', models.DateTimeField(verbose_name='sign date')),
                ('interestnum', models.IntegerField(verbose_name='luckly number')),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
